# Generated by Django 5.2.1 on 2025-05-19 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='direction',
        ),
        migrations.RemoveField(
            model_name='scheduleupload',
            name='direction',
        ),
        migrations.DeleteModel(
            name='ScheduleGet',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='Direction',
        ),
        migrations.DeleteModel(
            name='ScheduleUpload',
        ),
    ]
