# Generated by Django 5.2.1 on 2025-05-28 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_group_direction_and_more'),
        ('tuzilma', '0010_alter_direction_faculty_alter_direction_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='direction_key',
        ),
        migrations.RemoveField(
            model_name='student',
            name='faculty_key',
        ),
        migrations.RemoveField(
            model_name='student',
            name='level_key',
        ),
        migrations.AlterField(
            model_name='student',
            name='direction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tuzilma.direction'),
        ),
        migrations.AlterField(
            model_name='student',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tuzilma.faculty'),
        ),
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tuzilma.group', verbose_name='Guruh'),
        ),
        migrations.AlterField(
            model_name='student',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tuzilma.level'),
        ),
    ]
