# Generated by Django 5.2.1 on 2025-05-19 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('biomedical-engineering', 'Biotibbiyot muhandisligi 🧬'), ('nursing', 'Oliy hamshiralik ishi 💉'), ('medical-prevention', 'Tibbiy profilaktika ishi 🛡️'), ('general-medicine', 'Davolash ishi 🩺'), ('pharmacy', 'Farmatsiya 💊'), ('pediatrics', 'Pediatriya ishi 👶'), ('dentistry', 'Stomatologiya 🦷'), ('fundamental-medicine', 'Fundamental tibbiyot 🔬')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Ta'lim yo'nalishi ",
                'verbose_name_plural': "Ta'lim yo'nalishlari ",
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('course', models.SmallIntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('direction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tuzilma.direction')),
            ],
            options={
                'verbose_name': 'Guruh ',
                'verbose_name_plural': 'Guruhlar ',
            },
        ),
        migrations.CreateModel(
            name='ScheduleGet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.SmallIntegerField()),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tuzilma.direction')),
            ],
            options={
                'verbose_name': 'Jadval shabloni',
                'verbose_name_plural': 'Jadval shabloni',
            },
        ),
        migrations.CreateModel(
            name='ScheduleUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.SmallIntegerField()),
                ('file', models.FileField(upload_to='schedules/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('direction', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tuzilma.direction')),
            ],
            options={
                'verbose_name': 'Jadval Yuklash',
                'verbose_name_plural': 'Jadvallar ',
                'ordering': ['-created_at'],
            },
        ),
    ]
