# Generated by Django 5.2.1 on 2025-05-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuzilma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.CharField(choices=[('Biotibbiyot muhandisligi', 'Biotibbiyot muhandisligi'), ('Oliy hamshiralik ishi', 'Oliy hamshiralik ishi'), ('Tibbiy profilaktika ishi', 'Tibbiy profilaktika ishi'), ('Davolash ishi', 'Davolash ishi'), ('Farmatsiya', 'Farmatsiya'), ('Pediatriya ishi', 'Pediatriya ishi'), ('Stomatologiya ', 'Stomatologiya '), ('Fundamental tibbiyot', 'Fundamental tibbiyot')], max_length=100),
        ),
    ]
