# Generated by Django 5.2.1 on 2025-05-27 03:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuzilma', '0002_alter_direction_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Bakalavr', 'Bakalavr'), ('Magistr', 'Magistr'), ('Ordinatura', 'Kursant')], max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': "Ta'lim darajasi ",
                'verbose_name_plural': "Ta'lim darajalari ",
            },
        ),
        migrations.AddField(
            model_name='direction',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tuzilma.level'),
        ),
    ]
