# Generated by Django 5.2.1 on 2025-05-27 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuzilma', '0004_alter_direction_name_alter_level_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(choices=[('Bakalavr', 'Bakalavr'), ('Magistr', 'Magistr'), ('Ordinatura', 'Ordinatura')], max_length=100, unique=True),
        ),
    ]
