# Generated by Django 5.2.1 on 2025-05-27 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuzilma', '0005_alter_level_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.CharField(choices=[('Biotibbiyot muhandisligi', 'Biotibbiyot muhandisligi'), ('Oliy hamshiralik ishi', 'Oliy hamshiralik ishi'), ('Tibbiy profilaktika ishi', 'Tibbiy profilaktika ishi'), ('Davolash ishi', 'Davolash ishi'), ('Farmatsiya', 'Farmatsiya'), ('Pediatriya ishi', 'Pediatriya ishi'), ('Stomatologiya', 'Stomatologiya'), ('Fundamental tibbiyot', 'Fundamental tibbiyot'), ('Xalq tabobati', 'Xalq tabobati'), ('Akusherlik', 'Akusherlik'), ('Endokrinologiya', 'Endokrinologiya'), ('Gigiena', 'Gigiena'), ('Kardiologiya', 'Kardiologiya'), ('Laboratoria ishi', 'Laboratoria ishi'), ('Morfologiya', 'Morfologiya'), ('Otorinolaringologiya', 'Otorinolaringologiya'), ('Patologik anatomiya', 'Patologik anatomiya'), ('Rentgent texnikasi va texnologiyasi', 'Rentgent texnikasi va texnologiyasi'), ('Sog‘liqni saqlashni boshqarish va jamoat sog‘lig‘ini saqlash', 'Sog‘liqni saqlashni boshqarish va jamoat sog‘lig‘ini saqlash'), ('Terapiya', 'Terapiya'), ('Tibbiy-biologik apparatlar, tizimlar va majmualar', 'Tibbiy-biologik apparatlar, tizimlar va majmualar'), ('Umumiy onkologiya', 'Umumiy onkologiya'), ('Urologiya', 'Urologiya'), ('Xirurgiya', 'Xirurgiya'), ('Akusherlik va ginekologiya', 'Akusherlik va ginekologiya'), ('Allergologiya va klinik immunologiya', 'Allergologiya va klinik immunologiya'), ('Anesteziologiya va reanimatologiya', 'Anesteziologiya va reanimatologiya'), ('Bolalar anesteziologiya va reanimatologiyasi', 'Bolalar anesteziologiya va reanimatologiyasi'), ('Bolalar kardiorevmatalogiyasi', 'Bolalar kardiorevmatalogiyasi'), ('Bolalar nefrologiyasi', 'Bolalar nefrologiyasi'), ('Bolalar nevrologiyasi', 'Bolalar nevrologiyasi'), ('Bolalar va o‘smir qizlar ginekologiyasi', 'Bolalar va o‘smir qizlar ginekologiyasi'), ('Bolalar xirurgiyasi', 'Bolalar xirurgiyasi'), ('Dermatovenerologiya', 'Dermatovenerologiya'), ('Epidemiologiya', 'Epidemiologiya'), ('Ftiziatriya', 'Ftiziatriya'), ('Gemotologiya va transfuziologiya', 'Gemotologiya va transfuziologiya'), ('Ichki kasalliklar terapiya', 'Ichki kasalliklar terapiya'), ('Kommunal gigiena', 'Kommunal gigiena'), ('Mehnat gigienasi', 'Mehnat gigienasi'), ('Narkologiya', 'Narkologiya'), ('Nefrologiya', 'Nefrologiya'), ('Nefrologiya gtmodializ bilan', 'Nefrologiya gtmodializ bilan'), ('Neonatologiya', 'Neonatologiya'), ('Nevrologiya', 'Nevrologiya'), ('Neyroxirurgiya', 'Neyroxirurgiya'), ('Nutritsiologiya', 'Nutritsiologiya'), ('Oftalmologiya', 'Oftalmologiya'), ('Psixiatriya', 'Psixiatriya'), ('Pulmonologiya', 'Pulmonologiya'), ('Revmatologiya', 'Revmatologiya'), ('Terapevtik stomatologiya', 'Terapevtik stomatologiya'), ('Tibbiy psixologiya', 'Tibbiy psixologiya'), ('Tibbiy radiologiya', 'Tibbiy radiologiya'), ('Travmatologiya va ortopediya', 'Travmatologiya va ortopediya'), ('Yuqumli kasalliklar', 'Yuqumli kasalliklar'), ('Yuz jag‘ jarroxligi', 'Yuz jag‘ jarroxligi')], max_length=100, unique=True),
        ),
    ]
