# Generated by Django 5.2.1 on 2025-05-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuzilma', '0006_alter_direction_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
