# Generated by Django 5.2.1 on 2025-05-27 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuzilma', '0007_alter_direction_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='level',
        ),
        migrations.AlterField(
            model_name='group',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tuzilma.direction'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tuzilma.level')),
            ],
            options={
                'verbose_name': 'Fakultet ',
                'verbose_name_plural': 'Fakultetlar ',
            },
        ),
        migrations.AddField(
            model_name='direction',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tuzilma.faculty'),
        ),
    ]
