# Generated by Django 5.2.1 on 2025-05-28 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuzilma', '0009_direction_name_en_direction_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='faculty',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tuzilma.faculty', verbose_name='Fakultet'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Yo‘nalish nomi'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Yo‘nalish nomi'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Yo‘nalish nomi'),
        ),
        migrations.AlterField(
            model_name='direction',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Yo‘nalish nomi'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tuzilma.level', verbose_name='Daraja'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Fakultet nomi'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Fakultet nomi'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Fakultet nomi'),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, verbose_name='Fakultet nomi'),
        ),
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.SmallIntegerField(default=1, verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='group',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tuzilma.direction', verbose_name='Yo‘nalish'),
        ),
        migrations.AlterField(
            model_name='group',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Guruh nomi'),
        ),
        migrations.AlterField(
            model_name='level',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Faolmi'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name_en',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name_ru',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='level',
            name='name_uz',
            field=models.CharField(max_length=100, null=True, unique=True, verbose_name='Nomi'),
        ),
        migrations.AlterField(
            model_name='scheduleget',
            name='course',
            field=models.SmallIntegerField(verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='scheduleget',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tuzilma.direction', verbose_name='Yo‘nalish'),
        ),
        migrations.AlterField(
            model_name='scheduleupload',
            name='course',
            field=models.SmallIntegerField(verbose_name='Kurs'),
        ),
        migrations.AlterField(
            model_name='scheduleupload',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yuklangan vaqt'),
        ),
        migrations.AlterField(
            model_name='scheduleupload',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tuzilma.direction', verbose_name='Yo‘nalish'),
        ),
        migrations.AlterField(
            model_name='scheduleupload',
            name='file',
            field=models.FileField(upload_to='schedules/', verbose_name='Fayl'),
        ),
    ]
