# Generated by Django 5.2.1 on 2025-05-28 06:12

import django.core.files.storage
import django.core.validators
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuzilma', '0011_alter_scheduleupload_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleupload',
            options={'ordering': ['-created_at'], 'verbose_name': 'Jadval Yuklash', 'verbose_name_plural': 'Jadvallar'},
        ),
        migrations.AlterField(
            model_name='scheduleupload',
            name='file',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/schedules/', location=pathlib.PurePosixPath('/home/cbekoder/PycharmProjects/fjsti_register_bot/files/schedules')), upload_to='', validators=[django.core.validators.FileExtensionValidator(['xlsx'])], verbose_name='Fayl'),
        ),
        migrations.AlterUniqueTogether(
            name='scheduleupload',
            unique_together={('direction', 'course')},
        ),
    ]
