# Generated by Django 5.2.1 on 2025-05-28 06:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tuzilma', '0012_alter_scheduleupload_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleupload',
            name='file',
            field=models.FileField(upload_to='schedules/', validators=[django.core.validators.FileExtensionValidator(['xlsx'])], verbose_name='Fayl'),
        ),
    ]
