# Generated by Django 5.2.1 on 2025-05-28 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuzilma', '0013_alter_scheduleupload_file'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scheduleupload',
            unique_together=set(),
        ),
    ]
