# Generated by Django 5.2.1 on 2025-05-28 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuzilma', '0014_alter_scheduleupload_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scheduleupload',
            unique_together={('direction', 'course')},
        ),
    ]
