# Generated by Django 5.2.1 on 2025-05-28 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tuzilma', '0015_alter_scheduleupload_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='scheduleupload',
            unique_together=set(),
        ),
    ]
